site_name: Hash Stats
nav:  
- Home:  index.md  
- About:  about.md
- Primary Data Tables: data_tables.md
- SQL Views: SQL_views.md
- Reports:  reports.md

theme:  readthedocs
<!--stackedit_data:
eyJoaXN0b3J5IjpbLTExNTQ1NzY5NjMsNDUxNDQ2OTI3LDE1NT
g3NzQ1ODksLTEyOTQxMDA1NDddfQ==
-->