site_name: Hash Stats
nav:  
  - Home:  index.md  
  - About:  about.md
  - Primary Data Tables: data_tables.md
  - SQL Views: SQL_views.md
  - REST API: API.md
  - Reports:  reports.md
  - Run Registration Form: registration_form.md
  - Run Attendance Form: run_form.md

theme:  readthedocs
